In [1]:
import pandas as pd

# Load Titanic dataset
df = pd.read_csv("Titanic_Project/tested.csv")

# Display first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [2]:
# Select required columns
df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]

# Check missing values
print(df.isnull().sum())

# Fill missing Age values with the average age
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Convert Sex column into numbers
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

# Display first 5 rows
df.head()

Survived     0
Pclass       0
Sex          0
Age         86
Fare         1
dtype: int64

   Survived  Pclass  Sex   Age     Fare
0         0       3    0  34.5   7.8292
1         1       3    1  47.0   7.0000
2         0       2    0  62.0   9.6875
3         0       3    0  27.0   8.6625
4         1       3    1  22.0  12.2875

In [3]:
# Fill missing Fare value
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())

# Check missing values again
print(df.isnull().sum())

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

In [4]:
# Features (Input)
X = df[['Pclass', 'Sex', 'Age', 'Fare']]

# Target (Output)
y = df['Survived']

print(X.head())
print(y.head())

   Pclass  Sex   Age     Fare
0       3    0  34.5   7.8292
1       3    1  47.0   7.0000
2       2    0  62.0   9.6875
3       3    0  27.0   8.6625
4       3    1  22.0  12.2875
0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (334, 4)
Testing data: (84, 4)

In [6]:
from sklearn.linear_model import LogisticRegression

# Create model
model = LogisticRegression(max_iter=1000)

# Train model
model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Make predictions
y_pred = model.predict(X_test)

# Evaluate model
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

# Week 2 - Classification Model

## Model Used
- Logistic Regression

## Features
- Pclass
- Sex
- Age
- Fare

## Target
- Survived

## Evaluation Results
- Accuracy: 1.0
- Precision: 1.0
- Recall: 1.0
- F1 Score: 1.0

## Conclusion
The Logistic Regression model was successfully trained and evaluated on the Titanic dataset.